version: '3.2'

services:
  ldap:
    container_name: aginity-ldap
    image: osixia/openldap:1.3.0
    ports:
      - "389:389"
      - "636:636"
    env_file:
      - ./ldap.env
    volumes:
      - ./ldap:/data/ldif
